# Sub-issue metadata master for ESG issue groups.
# This file defines issue group / sub-issue mappings and representative metric ids.

ISSUE_GROUP_MASTER = {
    "Climate": {
        "esg_domain": "E",
        "issue_group_name": "Climate",
        "subissue_ids": ["Climate-01", "Climate-02", "Climate-03"],
    },
    "Energy": {
        "esg_domain": "E",
        "issue_group_name": "Energy",
        "subissue_ids": ["Energy-01", "Energy-02", "Energy-03"],
    },
    "Water": {
        "esg_domain": "E",
        "issue_group_name": "Water",
        "subissue_ids": ["Water-01", "Water-02", "Water-03"],
    },
    "Pollution": {
        "esg_domain": "E",
        "issue_group_name": "Pollution",
        "subissue_ids": ["Pollution-01", "Pollution-02", "Pollution-03"],
    },
    "Circularity": {
        "esg_domain": "E",
        "issue_group_name": "Circularity",
        "subissue_ids": ["Circularity-01", "Circularity-02", "Circularity-03"],
    },
    "Biodiversity": {
        "esg_domain": "E",
        "issue_group_name": "Biodiversity",
        "subissue_ids": ["Biodiversity-01", "Biodiversity-02", "Biodiversity-03"],
    },
    "Product_env": {
        "esg_domain": "E",
        "issue_group_name": "Product_env",
        "subissue_ids": ["Product_env-01", "Product_env-02", "Product_env-03"],
    },
    "Supply Chain_env": {
        "esg_domain": "E",
        "issue_group_name": "Supply Chain_env",
        "subissue_ids": ["Supply Chain_env-01", "Supply Chain_env-02", "Supply Chain_env-03"],
    },
    "Sustainable investment": {
        "esg_domain": "E",
        "issue_group_name": "Sustainable investment",
        "subissue_ids": ["Sustainable investment-01", "Sustainable investment-02", "Sustainable investment-03"],
    },
    "Labor": {
        "esg_domain": "S",
        "issue_group_name": "Labor",
        "subissue_ids": ["Labor-01", "Labor-02", "Labor-03"],
    },
    "Safety": {
        "esg_domain": "S",
        "issue_group_name": "Safety",
        "subissue_ids": ["Safety-01", "Safety-02", "Safety-03"],
    },
    "Talent": {
        "esg_domain": "S",
        "issue_group_name": "Talent",
        "subissue_ids": ["Talent-01", "Talent-02", "Talent-03"],
    },
    "Diversity": {
        "esg_domain": "S",
        "issue_group_name": "Diversity",
        "subissue_ids": ["Diversity-01", "Diversity-02", "Diversity-03"],
    },
    "Human Rights": {
        "esg_domain": "S",
        "issue_group_name": "Human Rights",
        "subissue_ids": ["Human Rights-01", "Human Rights-02", "Human Rights-03"],
    },
    "Supply Chain_social": {
        "esg_domain": "S",
        "issue_group_name": "Supply Chain_social",
        "subissue_ids": ["Supply Chain_social-01", "Supply Chain_social-02", "Supply Chain_social-03"],
    },
    "Community": {
        "esg_domain": "S",
        "issue_group_name": "Community",
        "subissue_ids": ["Community-01", "Community-02", "Community-03"],
    },
    "Product_resp": {
        "esg_domain": "S",
        "issue_group_name": "Product_resp",
        "subissue_ids": ["Product_resp-01", "Product_resp-02", "Product_resp-03"],
    },
    "Privacy": {
        "esg_domain": "S",
        "issue_group_name": "Privacy",
        "subissue_ids": ["Privacy-01", "Privacy-02", "Privacy-03"],
    },
    "Governance": {
        "esg_domain": "G",
        "issue_group_name": "Governance",
        "subissue_ids": ["Governance-01", "Governance-02", "Governance-03"],
    },
    "Risk": {
        "esg_domain": "G",
        "issue_group_name": "Risk",
        "subissue_ids": ["Risk-01", "Risk-02", "Risk-03"],
    },
    "Ethics": {
        "esg_domain": "G",
        "issue_group_name": "Ethics",
        "subissue_ids": ["Ethics-01", "Ethics-02", "Ethics-03"],
    },
    "Business Conduct": {
        "esg_domain": "G",
        "issue_group_name": "Business Conduct",
        "subissue_ids": ["Business Conduct-01", "Business Conduct-02", "Business Conduct-03"],
    },
    "Data Governance": {
        "esg_domain": "G",
        "issue_group_name": "Data Governance",
        "subissue_ids": ["Data Governance-01", "Data Governance-02", "Data Governance-03"],
    },
}

SUBISSUE_MASTER = {
    "Climate-01": {
        "issue_group_code": "Climate",
        "esg_domain": "E",
        "sub_issue_name": "기후 거버넌스·전환계획",
        "description": "이사회/경영진의 기후 감독, 전환계획, 시나리오 분석 및 감축 로드맵을 묶는 서브이슈",
        "base_metric_ids": ["E1-01", "E1-10", "E1-11", "E1-12"],
        "atomic_metric_ids": ["E1-01__A0096", "E1-10__A0112", "E1-11__A0113", "E1-12__A0114"],
    },
    "Climate-02": {
        "issue_group_code": "Climate",
        "esg_domain": "E",
        "sub_issue_name": "GHG 배출량·감축성과",
        "description": "Scope 1/2/3 배출량, 배출집약도, 감축목표 및 이행률을 관리하는 핵심 성과 서브이슈",
        "base_metric_ids": ["E1-03", "E1-04", "E1-05", "E1-06", "E1-07", "E1-08", "E1-15", "E1-16", "E1-17"],
        "atomic_metric_ids": ["E1-03__A0098", "E1-04__A0099", "E1-05__A0100", "E1-06__A0101", "E1-07__A0102", "E1-08__A0110", "E1-15__A0117"],
    },
    "Climate-03": {
        "issue_group_code": "Climate",
        "esg_domain": "E",
        "sub_issue_name": "기후 재무영향·탄소가격",
        "description": "기후 리스크/기회가 비용, CAPEX/OPEX, 내부탄소가격 등 재무항목에 미치는 영향을 설명하는 서브이슈",
        "base_metric_ids": ["E1-13", "E1-14", "G0-43", "G0-36"],
        "atomic_metric_ids": ["E1-13__A0115", "E1-14__A0116", "G0-43__A0087", "G0-36__A0080"],
    },
    "Energy-01": {
        "issue_group_code": "Energy",
        "esg_domain": "E",
        "sub_issue_name": "에너지 사용량·에너지원 믹스",
        "description": "총 에너지 사용량과 재생/비재생 전력, LNG, 연료, 스팀 등 에너지원별 사용량",
        "base_metric_ids": ["E2-01", "E2-02", "E2-05", "E2-06", "E2-07", "E2-08", "E2-09", "E2-10"],
        "atomic_metric_ids": ["E2-01__A0123", "E2-02__A0129", "E2-05__A0137", "E2-06__A0138", "E2-07__A0139"],
    },
    "Energy-02": {
        "issue_group_code": "Energy",
        "esg_domain": "E",
        "sub_issue_name": "재생에너지 전환",
        "description": "재생에너지 사용량, 비율, 구매/자가발전/인증서 활용 등 에너지 전환 성과",
        "base_metric_ids": ["E2-03", "E2-06"],
        "atomic_metric_ids": ["E2-03__A0135", "E2-06__A0138"],
    },
    "Energy-03": {
        "issue_group_code": "Energy",
        "esg_domain": "E",
        "sub_issue_name": "에너지 효율·집약도",
        "description": "에너지 절감률, 집약도, 제품/차량당 에너지 사용량 등 효율 개선 성과",
        "base_metric_ids": ["E2-04", "E2-11"],
        "atomic_metric_ids": ["E2-04__A0136", "E2-11__A0143"],
    },
    "Water-01": {
        "issue_group_code": "Water",
        "esg_domain": "E",
        "sub_issue_name": "취수·수원별 물 사용",
        "description": "지표수/지하수/상수도 등 수원별 취수량과 사업장별 용수 사용량",
        "base_metric_ids": ["E3-01", "E3-06", "E3-07", "E3-08"],
        "atomic_metric_ids": ["E3-01__A0144", "E3-06__A0189", "E3-07__A0198", "E3-08__A0207"],
    },
    "Water-02": {
        "issue_group_code": "Water",
        "esg_domain": "E",
        "sub_issue_name": "방류·수질오염 관리",
        "description": "방류량, 오염물질, 수질 관리 기준 및 방류 리스크를 관리하는 서브이슈",
        "base_metric_ids": ["E3-02", "E4-09", "E4-10"],
        "atomic_metric_ids": ["E3-02__A0153", "E4-09__A0255", "E4-10__A0264"],
    },
    "Water-03": {
        "issue_group_code": "Water",
        "esg_domain": "E",
        "sub_issue_name": "용수 재이용·수자원 리스크",
        "description": "재이용수 사용량/비율, 물 스트레스 지역, 수자원 리스크 평가 체계",
        "base_metric_ids": ["E3-03", "E3-04", "E3-05", "E3-09", "E3-10", "E3-11"],
        "atomic_metric_ids": ["E3-03__A0162", "E3-04__A0171", "E3-05__A0180", "E3-10__A0225"],
    },
    "Pollution-01": {
        "issue_group_code": "Pollution",
        "esg_domain": "E",
        "sub_issue_name": "대기오염물질 배출",
        "description": "SOx, NOx, PM 등 주요 대기오염물질 배출량과 집약도",
        "base_metric_ids": ["E4-01", "E4-05", "E4-06", "E4-07", "E4-08"],
        "atomic_metric_ids": ["E4-01__A0235", "E4-05__A0251", "E4-06__A0252", "E4-07__A0253", "E4-08__A0254"],
    },
    "Pollution-02": {
        "issue_group_code": "Pollution",
        "esg_domain": "E",
        "sub_issue_name": "유해화학물질·수질오염 관리",
        "description": "유해/우려 화학물질 관리, 수질오염물질, 화학물질 규제 대응 체계",
        "base_metric_ids": ["E4-02", "E4-09", "E4-10", "G102-01"],
        "atomic_metric_ids": ["E4-02__A0239", "E4-09__A0255", "E4-10__A0264", "G102-01__A0682"],
    },
    "Pollution-03": {
        "issue_group_code": "Pollution",
        "esg_domain": "E",
        "sub_issue_name": "환경사고·법규위반",
        "description": "누출/유출 사고, 환경 법규 위반, 벌금 및 재발방지 조치",
        "base_metric_ids": ["E4-03", "E4-04", "G2-08", "G2-09"],
        "atomic_metric_ids": ["E4-03__A0243", "E4-04__A0247", "G2-08__A0584", "G2-09__A0588"],
    },
    "Circularity-01": {
        "issue_group_code": "Circularity",
        "esg_domain": "E",
        "sub_issue_name": "폐기물 발생·처리",
        "description": "유해/비유해 폐기물 발생량과 재활용, 매립, 소각 등 처리방법별 데이터",
        "base_metric_ids": ["E5-01", "E5-02", "E5-12", "E5-13"],
        "atomic_metric_ids": ["E5-01__A0288", "E5-02__A0296", "E5-12__A0333", "E5-13__A0334"],
    },
    "Circularity-02": {
        "issue_group_code": "Circularity",
        "esg_domain": "E",
        "sub_issue_name": "재활용·회수·순환성과",
        "description": "폐기물 재활용/회수율, 처분비율, 순환경제 성과 관리",
        "base_metric_ids": ["E5-03", "E5-04"],
        "atomic_metric_ids": ["E5-03__A0304", "E5-04__A0312"],
    },
    "Circularity-03": {
        "issue_group_code": "Circularity",
        "esg_domain": "E",
        "sub_issue_name": "원재료 사용·재생원료",
        "description": "철강/알루미늄 등 주요 원재료 사용량, 스크랩, 재생원료 투입비율",
        "base_metric_ids": ["E5-05", "E5-06", "E5-07", "E5-08", "E5-09", "E5-10", "E5-11"],
        "atomic_metric_ids": ["E5-05__A0316", "E5-06__A0324", "E5-09__A0330", "E5-10__A0331"],
    },
    "Biodiversity-01": {
        "issue_group_code": "Biodiversity",
        "esg_domain": "E",
        "sub_issue_name": "민감지역·보호구역 노출",
        "description": "생물다양성 민감지역 인접 사업장 여부와 위치/규모/활동 범위",
        "base_metric_ids": ["E6-01"],
        "atomic_metric_ids": ["E6-01__A0342", "E6-01__A0343", "E6-01__A0344"],
    },
    "Biodiversity-02": {
        "issue_group_code": "Biodiversity",
        "esg_domain": "E",
        "sub_issue_name": "생물다양성 영향평가",
        "description": "사업장·프로젝트의 생태계 영향평가 체계와 주요 영향 결과",
        "base_metric_ids": ["E6-02"],
        "atomic_metric_ids": ["E6-02__A0345", "E6-02__A0346", "E6-02__A0347"],
    },
    "Biodiversity-03": {
        "issue_group_code": "Biodiversity",
        "esg_domain": "E",
        "sub_issue_name": "복원·보전 활동",
        "description": "훼손지역 복원, 보전 프로그램, 목표와 진척도",
        "base_metric_ids": ["E6-03"],
        "atomic_metric_ids": ["E6-03__A0348"],
    },
    "Product_env-01": {
        "issue_group_code": "Product_env",
        "esg_domain": "E",
        "sub_issue_name": "친환경 제품 기준·분류",
        "description": "친환경 제품 정의, 적용 기준, 제품군별 분류 체계",
        "base_metric_ids": ["E7-01"],
        "atomic_metric_ids": ["E7-01__A0349"],
    },
    "Product_env-02": {
        "issue_group_code": "Product_env",
        "esg_domain": "E",
        "sub_issue_name": "제품 LCA·제품탄소",
        "description": "제품 LCA 수행 여부, 제품/모델별 탄소발자국 및 인증 범위",
        "base_metric_ids": ["E7-02", "E7-07"],
        "atomic_metric_ids": ["E7-02__A0350", "E7-07__A0357"],
    },
    "Product_env-03": {
        "issue_group_code": "Product_env",
        "esg_domain": "E",
        "sub_issue_name": "친환경 제품 매출·판매",
        "description": "친환경/저탄소 제품 판매비율, 친환경 차량·부품 매출 성과",
        "base_metric_ids": ["E7-06", "E7-04"],
        "atomic_metric_ids": ["E7-06__A0356", "E7-04__A0354"],
    },
    "Supply Chain_env-01": {
        "issue_group_code": "Supply Chain_env",
        "esg_domain": "E",
        "sub_issue_name": "공급망 환경평가 커버리지",
        "description": "1차/2차/3차 협력사에 대한 환경 평가·스크리닝 적용 범위",
        "base_metric_ids": ["E7-03"],
        "atomic_metric_ids": ["E7-03__A0351", "E7-03__A0352", "E7-03__A0353"],
    },
    "Supply Chain_env-02": {
        "issue_group_code": "Supply Chain_env",
        "esg_domain": "E",
        "sub_issue_name": "협력사 환경개선·CAP",
        "description": "환경 리스크 협력사 개선계획, CAPA 이행률, 개선 완료 현황",
        "base_metric_ids": ["E7-03", "S6-05"],
        "atomic_metric_ids": ["E7-03__A0351", "S6-05__A0521"],
    },
    "Supply Chain_env-03": {
        "issue_group_code": "Supply Chain_env",
        "esg_domain": "E",
        "sub_issue_name": "공급망 환경 데이터 품질",
        "description": "협력사 Scope 3, 원재료 환경정보, 증빙 수집률과 검증 범위",
        "base_metric_ids": ["E1-07", "E5-05", "E7-03"],
        "atomic_metric_ids": ["E1-07__A0102", "E5-05__A0316", "E7-03__A0351"],
    },
    "Sustainable investment-01": {
        "issue_group_code": "Sustainable investment",
        "esg_domain": "E",
        "sub_issue_name": "환경투자·CAPEX/OPEX",
        "description": "기후·환경 개선 투자, CAPEX/OPEX, 환경 투자비 집행 현황",
        "base_metric_ids": ["E1-14", "E7-04", "G0-43"],
        "atomic_metric_ids": ["E1-14__A0116", "E7-04__A0354", "G0-43__A0087"],
    },
    "Sustainable investment-02": {
        "issue_group_code": "Sustainable investment",
        "esg_domain": "E",
        "sub_issue_name": "친환경 구매·조달비",
        "description": "녹색구매, 재생원료/친환경 제품 구매 지출과 비율",
        "base_metric_ids": ["E7-05", "E5-06"],
        "atomic_metric_ids": ["E7-05__A0355", "E5-06__A0324"],
    },
    "Sustainable investment-03": {
        "issue_group_code": "Sustainable investment",
        "esg_domain": "E",
        "sub_issue_name": "R&D·전환기술 투자",
        "description": "친환경 기술, 저탄소 제품, EV/고전압 안전 등 미래 전환 R&D 투자",
        "base_metric_ids": ["G0-41", "G0-42", "E7-06", "S101-03"],
        "atomic_metric_ids": ["G0-41__A0085", "G0-42__A0086", "E7-06__A0356", "S101-03__A0672"],
    },
    "Labor-01": {
        "issue_group_code": "Labor",
        "esg_domain": "S",
        "sub_issue_name": "고용구조·인력구성",
        "description": "임직원 수, 지역/성별/고용형태/근무형태/직군별 인력 구조",
        "base_metric_ids": ["S1-01", "S1-02", "S1-06", "S1-07", "S1-08", "S1-09", "S1-10"],
        "atomic_metric_ids": ["S1-02__A0359", "S1-06__A0378", "S1-07__A0394", "S1-08__A0410"],
    },
    "Labor-02": {
        "issue_group_code": "Labor",
        "esg_domain": "S",
        "sub_issue_name": "채용·이직·고용안정",
        "description": "신규채용률, 이직률, 비정규/간접고용, 육아휴직 복귀율",
        "base_metric_ids": ["S1-03", "S1-04", "S1-11", "S1-14", "S1-16"],
        "atomic_metric_ids": ["S1-03__A0375", "S1-04__A0376", "S1-11__A0443", "S1-14__A0446", "S1-16__A0448"],
    },
    "Labor-03": {
        "issue_group_code": "Labor",
        "esg_domain": "S",
        "sub_issue_name": "노사관계·사회적 대화",
        "description": "노동관행 정책, 사회적 대화 체계, 단체협약 적용률, 파업일수",
        "base_metric_ids": ["S1-01", "S1-05", "S1-12", "S1-13"],
        "atomic_metric_ids": ["S1-01__A0358", "S1-05__A0377", "S1-12__A0444", "S1-13__A0445"],
    },
    "Safety-01": {
        "issue_group_code": "Safety",
        "esg_domain": "S",
        "sub_issue_name": "안전보건 관리체계",
        "description": "안전보건 정책, 위험성평가, 사고조사, 참여체계 및 교육체계",
        "base_metric_ids": ["S2-01", "S2-02", "S2-03", "S2-04"],
        "atomic_metric_ids": ["S2-01__A0449", "S2-02__A0450", "S2-03__A0451", "S2-04__A0452"],
    },
    "Safety-02": {
        "issue_group_code": "Safety",
        "esg_domain": "S",
        "sub_issue_name": "재해율·중대재해",
        "description": "TRIR/LTIFR, 사망사고, 중대재해, 도급작업자 재해율",
        "base_metric_ids": ["S2-05", "S2-06", "S100-01", "S102-01"],
        "atomic_metric_ids": ["S2-05__A0453", "S2-06__A0454", "S100-01__A0666", "S102-01__A0673"],
    },
    "Safety-03": {
        "issue_group_code": "Safety",
        "esg_domain": "S",
        "sub_issue_name": "고위험 작업 통제",
        "description": "작업허가 적용률, 고위험 작업 교육, 공정안전 incident 관리",
        "base_metric_ids": ["S100-02", "S101-03", "S102-01"],
        "atomic_metric_ids": ["S100-02__A0667", "S101-03__A0672", "S102-01__A0673"],
    },
    "Talent-01": {
        "issue_group_code": "Talent",
        "esg_domain": "S",
        "sub_issue_name": "교육훈련·역량개발",
        "description": "교육훈련 정책, 1인당 교육시간, 교육비, 교육일수",
        "base_metric_ids": ["S3-01", "S3-02", "S3-05", "S3-06", "S3-07"],
        "atomic_metric_ids": ["S3-01__A0458", "S3-02__A0459", "S3-05__A0462", "S3-06__A0463", "S3-07__A0464"],
    },
    "Talent-02": {
        "issue_group_code": "Talent",
        "esg_domain": "S",
        "sub_issue_name": "성과·경력개발",
        "description": "성과평가 실시율, 경력개발 평가, 내부충원율, 인턴 전환율",
        "base_metric_ids": ["S3-03", "S3-08", "S1-15"],
        "atomic_metric_ids": ["S3-03__A0460", "S3-08__A0465", "S1-15__A0447"],
    },
    "Talent-03": {
        "issue_group_code": "Talent",
        "esg_domain": "S",
        "sub_issue_name": "미래역량·핵심직무",
        "description": "핵심직무 교육 목표, EV/고전압 안전교육 이수율 등 전환역량",
        "base_metric_ids": ["S3-04", "S101-03"],
        "atomic_metric_ids": ["S3-04__A0461", "S101-03__A0672"],
    },
    "Diversity-01": {
        "issue_group_code": "Diversity",
        "esg_domain": "S",
        "sub_issue_name": "다양성·차별금지 정책",
        "description": "DEI 정책, 차별금지, 장애인 고용 등 포용 체계",
        "base_metric_ids": ["S4-01", "S4-12"],
        "atomic_metric_ids": ["S4-01__A0466", "S4-12__A0497"],
    },
    "Diversity-02": {
        "issue_group_code": "Diversity",
        "esg_domain": "S",
        "sub_issue_name": "성별·직급별 다양성",
        "description": "여성 임직원/관리자/임원/핵심직무 비율 및 직군별 다양성",
        "base_metric_ids": ["S4-02", "S4-05", "S4-06", "S4-07", "S4-08", "S4-09", "S4-10"],
        "atomic_metric_ids": ["S4-02__A0469", "S4-05__A0478", "S4-06__A0481", "S4-07__A0484"],
    },
    "Diversity-03": {
        "issue_group_code": "Diversity",
        "esg_domain": "S",
        "sub_issue_name": "임금격차·차별 incident",
        "description": "성별 임금격차, 보수격차, 차별·괴롭힘 incident 및 조치",
        "base_metric_ids": ["S4-03", "S4-04", "S4-11"],
        "atomic_metric_ids": ["S4-03__A0472", "S4-04__A0475", "S4-11__A0496"],
    },
    "Human Rights-01": {
        "issue_group_code": "Human Rights",
        "esg_domain": "S",
        "sub_issue_name": "인권정책·국제기준",
        "description": "인권정책, 국제기준 준수, 적용범위, 교육 및 내재화",
        "base_metric_ids": ["S5-01", "S5-02", "S5-03"],
        "atomic_metric_ids": ["S5-01__A0500", "S5-02__A0501", "S5-03__A0502"],
    },
    "Human Rights-02": {
        "issue_group_code": "Human Rights",
        "esg_domain": "S",
        "sub_issue_name": "인권영향평가·중요 인권이슈",
        "description": "중요 인권이슈 식별, 영향평가 결과, 고위험 사업장/그룹",
        "base_metric_ids": ["S5-02", "S6-03"],
        "atomic_metric_ids": ["S5-02__A0501", "S6-03__A0515"],
    },
    "Human Rights-03": {
        "issue_group_code": "Human Rights",
        "esg_domain": "S",
        "sub_issue_name": "grievance·구제·incident",
        "description": "인권 grievance 접수·종결률·처리일수, 중대한 인권 incident와 remedy",
        "base_metric_ids": ["S5-03", "S5-04", "S5-05", "S5-06"],
        "atomic_metric_ids": ["S5-03__A0502", "S5-04__A0503", "S5-05__A0504", "S5-06__A0505"],
    },
    "Supply Chain_social-01": {
        "issue_group_code": "Supply Chain_social",
        "esg_domain": "S",
        "sub_issue_name": "협력사 노동·인권 기준",
        "description": "공급업체 행동규범, 노동·인권 요구사항, 계약 반영 범위",
        "base_metric_ids": ["S6-01", "G4-01"],
        "atomic_metric_ids": ["S6-01__A0509", "G4-01__A0598"],
    },
    "Supply Chain_social-02": {
        "issue_group_code": "Supply Chain_social",
        "esg_domain": "S",
        "sub_issue_name": "공급망 실사·감사·CAP",
        "description": "사회실사/감사 수행률, CAP 완료율, 개선조치 관리",
        "base_metric_ids": ["S6-02", "S6-04", "S6-05", "S101-01"],
        "atomic_metric_ids": ["S6-02__A0512", "S6-04__A0518", "S6-05__A0521", "S101-01__A0668"],
    },
    "Supply Chain_social-03": {
        "issue_group_code": "Supply Chain_social",
        "esg_domain": "S",
        "sub_issue_name": "고위험 공급업체·인권위반",
        "description": "고위험 공급업체 비중, 공급망 중대 인권위반 및 grievance 건수",
        "base_metric_ids": ["S6-03", "S6-06"],
        "atomic_metric_ids": ["S6-03__A0515", "S6-06__A0524"],
    },
    "Community-01": {
        "issue_group_code": "Community",
        "esg_domain": "S",
        "sub_issue_name": "지역사회 영향평가·참여",
        "description": "지역사회 참여, 영향평가 실시율, 이해관계자 소통 체계",
        "base_metric_ids": ["S7-01", "S7-02"],
        "atomic_metric_ids": ["S7-01__A0527", "S7-02__A0528"],
    },
    "Community-02": {
        "issue_group_code": "Community",
        "esg_domain": "S",
        "sub_issue_name": "지역사회 grievance·구제",
        "description": "지역사회 grievance 접수건수, 종결률, 평균 처리일수 및 시정조치",
        "base_metric_ids": ["S7-02", "S7-03"],
        "atomic_metric_ids": ["S7-02__A0528", "S7-03__A0529"],
    },
    "Community-03": {
        "issue_group_code": "Community",
        "esg_domain": "S",
        "sub_issue_name": "사회공헌·지역투자",
        "description": "지역사회 투자, 기부, 상생 프로그램, 임직원 봉사, 협회 후원",
        "base_metric_ids": ["S7-04", "S7-05", "S7-06", "S7-07", "G0-35"],
        "atomic_metric_ids": ["S7-04__A0530", "S7-05__A0531", "S7-06__A0532", "S7-07__A0533", "G0-35__A0079"],
    },
    "Product_resp-01": {
        "issue_group_code": "Product_resp",
        "esg_domain": "S",
        "sub_issue_name": "제품안전·품질관리 체계",
        "description": "제품안전, 품질관리, 안전성 평가 적용 범위와 인증 커버리지",
        "base_metric_ids": ["S8-01", "S8-04", "S8-05"],
        "atomic_metric_ids": ["S8-01__A0534", "S8-04__A0540", "S8-05__A0541"],
    },
    "Product_resp-02": {
        "issue_group_code": "Product_resp",
        "esg_domain": "S",
        "sub_issue_name": "리콜·품질 클레임",
        "description": "제품안전 법규위반, 리콜/field action, 품질 클레임과 종결률",
        "base_metric_ids": ["S8-02", "S8-03", "S101-02", "S8-08"],
        "atomic_metric_ids": ["S8-02__A0535", "S8-03__A0539", "S101-02__A0671", "S8-08__A0547"],
    },
    "Product_resp-03": {
        "issue_group_code": "Product_resp",
        "esg_domain": "S",
        "sub_issue_name": "고객만족·제품 정보",
        "description": "고객만족도, SDS/위해성 정보 최신화, 안전 결함 조사",
        "base_metric_ids": ["S8-07", "S8-09", "S102-02"],
        "atomic_metric_ids": ["S8-07__A0543", "S8-09__A0551", "S102-02__A0677"],
    },
    "Privacy-01": {
        "issue_group_code": "Privacy",
        "esg_domain": "S",
        "sub_issue_name": "개인정보보호 관리체계",
        "description": "개인정보보호 정책, 관리체계, 책임조직 및 절차",
        "base_metric_ids": ["S9-01"],
        "atomic_metric_ids": ["S9-01__A0552"],
    },
    "Privacy-02": {
        "issue_group_code": "Privacy",
        "esg_domain": "S",
        "sub_issue_name": "침해·유출·민원·제재",
        "description": "개인정보 유출/침해 건수, 고객 불만, 벌금·제재액",
        "base_metric_ids": ["S9-02", "S9-03", "G2-06"],
        "atomic_metric_ids": ["S9-02__A0553", "S9-03__A0554", "G2-06__A0579"],
    },
    "Privacy-03": {
        "issue_group_code": "Privacy",
        "esg_domain": "S",
        "sub_issue_name": "정보보안 incident 대응",
        "description": "정보보안 incident, 조사, 재발방지, 시스템 보안통제",
        "base_metric_ids": ["S9-04", "G5-02"],
        "atomic_metric_ids": ["S9-04__A0558", "G5-02__A0610"],
    },
    "Governance-01": {
        "issue_group_code": "Governance",
        "esg_domain": "G",
        "sub_issue_name": "이사회·ESG 감독구조",
        "description": "이사회 구조, ESG 감독기구, 위원회 구성과 승인 규정",
        "base_metric_ids": ["G1-01", "G0-17", "G0-18", "G0-19"],
        "atomic_metric_ids": ["G1-01__A0562", "G0-17__A0044", "G0-18__A0045", "G0-19__A0046"],
    },
    "Governance-02": {
        "issue_group_code": "Governance",
        "esg_domain": "G",
        "sub_issue_name": "책임·권한·R&R",
        "description": "ESG 경영진 책임, R&R 매트릭스, 보고라인, 안건 검토 횟수",
        "base_metric_ids": ["G1-02", "G1-03", "G0-19"],
        "atomic_metric_ids": ["G1-02__A0563", "G1-03__A0564", "G0-19__A0046"],
    },
    "Governance-03": {
        "issue_group_code": "Governance",
        "esg_domain": "G",
        "sub_issue_name": "독립성·보상·역량",
        "description": "이사회 독립성, 다양성, ESG 교육, 보상 연계 여부",
        "base_metric_ids": ["G1-04", "G1-05", "G1-06", "G0-20", "G0-21"],
        "atomic_metric_ids": ["G1-04__A0565", "G1-05__A0566", "G1-06__A0567", "G0-20__A0047"],
    },
    "Risk-01": {
        "issue_group_code": "Risk",
        "esg_domain": "G",
        "sub_issue_name": "ESG 리스크·기회 관리",
        "description": "ESG 리스크/기회 식별, 평가, 대응 프로세스와 materiality 연계",
        "base_metric_ids": ["G2-01", "G0-23", "G0-24"],
        "atomic_metric_ids": ["G2-01__A0571", "G0-23__A0055", "G0-24__A0059"],
    },
    "Risk-02": {
        "issue_group_code": "Risk",
        "esg_domain": "G",
        "sub_issue_name": "법규준수·내부통제",
        "description": "법규 레지스터, 내부통제, 승인 워크플로우, 중대한 법규 위반",
        "base_metric_ids": ["G2-02", "G2-03", "G2-04", "G100-01"],
        "atomic_metric_ids": ["G2-02__A0572", "G2-03__A0573", "G2-04__A0574", "G100-01__A0678"],
    },
    "Risk-03": {
        "issue_group_code": "Risk",
        "esg_domain": "G",
        "sub_issue_name": "incident escalation·제재",
        "description": "중대 ESG incident escalation, 환경/광고/개인정보 등 규제 사건과 벌금",
        "base_metric_ids": ["G2-05", "G2-06", "G2-07", "G2-08", "G2-09"],
        "atomic_metric_ids": ["G2-05__A0578", "G2-06__A0579", "G2-07__A0580", "G2-08__A0584", "G2-09__A0588"],
    },
    "Ethics-01": {
        "issue_group_code": "Ethics",
        "esg_domain": "G",
        "sub_issue_name": "윤리규범·부패방지 정책",
        "description": "윤리규범, 부패방지 정책, 적용 범위와 내재화 체계",
        "base_metric_ids": ["G3-01", "G0-26", "G0-27"],
        "atomic_metric_ids": ["G3-01__A0589", "G0-26__A0067", "G0-27__A0068"],
    },
    "Ethics-02": {
        "issue_group_code": "Ethics",
        "esg_domain": "G",
        "sub_issue_name": "윤리교육·제3자 리스크",
        "description": "윤리/부패방지 교육 이수율, 고위험 거래/제3자 리스크 평가",
        "base_metric_ids": ["G3-02", "G3-03", "G1-07", "G1-08", "G1-09"],
        "atomic_metric_ids": ["G3-02__A0590", "G3-03__A0591", "G1-07__A0568", "G1-08__A0569", "G1-09__A0570"],
    },
    "Ethics-03": {
        "issue_group_code": "Ethics",
        "esg_domain": "G",
        "sub_issue_name": "제보·부패 incident·징계",
        "description": "내부제보 채널, 보복금지, 접수/종결률, 부패·사기 incident 및 징계",
        "base_metric_ids": ["G3-04", "G3-05", "G3-06", "G0-28"],
        "atomic_metric_ids": ["G3-04__A0592", "G3-05__A0596", "G3-06__A0597", "G0-28__A0069"],
    },
    "Business Conduct-01": {
        "issue_group_code": "Business Conduct",
        "esg_domain": "G",
        "sub_issue_name": "책임구매·공급업체 준법",
        "description": "책임구매 정책, 공급업체 준법 요구사항, 계약/평가 반영",
        "base_metric_ids": ["G4-01", "S6-01"],
        "atomic_metric_ids": ["G4-01__A0598", "S6-01__A0509"],
    },
    "Business Conduct-02": {
        "issue_group_code": "Business Conduct",
        "esg_domain": "G",
        "sub_issue_name": "거래관행·지급·세무",
        "description": "협력사 평균 지급기간, 세무 거버넌스, 세무 리스크 관리",
        "base_metric_ids": ["G4-02", "G4-04"],
        "atomic_metric_ids": ["G4-02__A0601", "G4-04__A0605"],
    },
    "Business Conduct-03": {
        "issue_group_code": "Business Conduct",
        "esg_domain": "G",
        "sub_issue_name": "공공정책·협회·후원",
        "description": "정치후원, 협회비, 로비/공공정책 참여 관리",
        "base_metric_ids": ["G4-03", "G4-05", "S7-07"],
        "atomic_metric_ids": ["G4-03__A0602", "G4-05__A0608", "S7-07__A0533"],
    },
    "Data Governance-01": {
        "issue_group_code": "Data Governance",
        "esg_domain": "G",
        "sub_issue_name": "ESG 데이터 사전·기준관리",
        "description": "ESG 데이터 사전, metric/atomic row 정의, 데이터 오너십 관리",
        "base_metric_ids": ["G5-01", "G2-03"],
        "atomic_metric_ids": ["G5-01__A0609", "G2-03__A0573"],
    },
    "Data Governance-02": {
        "issue_group_code": "Data Governance",
        "esg_domain": "G",
        "sub_issue_name": "증빙 보관·변경이력",
        "description": "증빙 보관, 변경이력, audit trail, 원천 추적성 관리",
        "base_metric_ids": ["G5-02"],
        "atomic_metric_ids": ["G5-02__A0610"],
    },
    "Data Governance-03": {
        "issue_group_code": "Data Governance",
        "esg_domain": "G",
        "sub_issue_name": "내부검증·외부 assurance",
        "description": "내부검증 및 외부 assurance 범위, 계획, 결과 관리",
        "base_metric_ids": ["G5-03", "G0-25"],
        "atomic_metric_ids": ["G5-03__A0611", "G0-25__A0063"],
    },
}
