services:
  selenium-chrome:
    image: selenium/standalone-chrome:latest
    shm_size: 2gb
    ports:
      - "4444:4444"
      - "7900:7900"
    networks:
      - airflow_default
    environment:
      - SE_NODE_MAX_SESSIONS=4

networks:
  airflow_default:
    external: true
